import { Dimensions, StyleSheet } from "react-native";
import { colors } from "../../global/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
    padding: 25,
  },
  boxTop: {
    height: Dimensions.get("window").height / 3.5,
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: 80,
    height: 80,
  },
  title: {
    marginTop: 25,
    fontSize: 24,
    fontFamily: "Roleway",
    fontWeight: "bold",
    color: "#ffffff",
  },
  subTitle: {
    marginTop: 5,
    fontSize: 16,
    fontFamily: "RolewayRegular",
    textAlign: "center",
    color: "#ffffff",
  },
  boxMid: {
    width: "100%",
    height: Dimensions.get("window").height / 2.7,
    alignItems: "center",
  },
  inputBox: {
    backgroundColor: colors.inputBackground,
    width: "100%",
    height: 55,
    padding: 8,
    borderRadius: 16,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
  },
  textInput: {
    flex: 1,
    marginLeft: 10,
    color: "#ffffff",
    fontSize: 16,
  },
  icon: {
    width: 40,
    height: 40,
    backgroundColor: "#6b6798",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  buttonLogin: {
    width: "100%",
    height: 55,
    marginTop: 24,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 16,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
  },
  textButton: {
    fontSize: 20,
    fontFamily: "RolewayRegular",
    fontWeight: "bold",
    color: colors.background,
  },
  boxBottom: {
    height: Dimensions.get("window").height / 4,
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginVertical: 24,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: "#4B4376",
  },
  dividerText: {
    marginHorizontal: 12,
    color: "#B9B5D3",
    fontSize: 14,
    fontFamily: "RolewayRegular",
  },
  socialLogins: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingLeft: 20,
    paddingRight: 20,
  },
  socialLoginButton: {
    width: 50,
    height: 50,
    backgroundColor: colors.inputBackground,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
  },
  socialLoginIcon: {
    width: 30,
    height: 30,
  },
  signup: {
    marginTop: "auto",
    marginBottom: 10,
    backgroundColor: colors.inputBackground,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: 55,
    borderRadius: 16,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
  },
  textSignUp: {
    color: "#B9B5D3",
    fontSize: 15,
    fontFamily: "RolewayRegular",
  },
  textButtonSignUp: {
    color: colors.primary,
    fontSize: 15,
    fontFamily: "RolewayRegular",
    fontWeight: "bold",
  },
});
